global:
  resolve_timeout: 1m
route:
  receiver: feishu
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: feishu
    webhook_configs:
      - url: 'http://localhost:8989/webhook'
        send_resolved: false
        max_alerts: 3


